### ISSUE TITLE
module name not to PEP8 standard

### ISSUE THREAD

**Issue by Xiaorui-Huang** [EdwardHaoranLee/WoodokuLearn#30]
Also, I found that the module name should be short, and all-lowercase, according to [doc](https://peps.python.org/pep-0008/#package-and-module-names). Then should we keep camelcase names in src/Entity or should we change the name of test files? I am fine with either way.

_Originally posted by @YANLING-H in https://github.com/EdwardHaoranLee/WoodokuLearn/pull/23#discussion_r925899032_

**Comment by Xiaorui-Huang** [comment]
I think our file structure is incorrect then, should all be lowercase with underscores.

see https://github.com/pytorch/pytorch for example
@EdwardHaoranLee  any comment?
@YANLING-H any suggestions?

**Comment by EdwardHaoranLee** [comment]
Due Jul 20, 2022
